#!/bin/sh
set -ex

while [ -z "$RPI_KIOSK_URL" ]; do
    read -p "Enter Kiosk URL: " RPI_KIOSK_URL
done

echo "Using RPI_KIOSK_URL: $RPI_KIOSK_URL"

test -d /etc/rpi-chromium-kiosk/ || mkdir /etc/rpi-chromium-kiosk/
test -f /etc/rpi-chromium-kiosk/env && rm /etc/rpi-chromium-kiosk/env
echo "DISPLAY=:0.0" >> /etc/rpi-chromium-kiosk/env
echo "XAUTHORITY=/home/pi/.Xauthority" >> /etc/rpi-chromium-kiosk/env
echo "RPI_KIOSK_URL=$RPI_KIOSK_URL" >> /etc/rpi-chromium-kiosk/env

for i in `cat /etc/rpi-chromium-kiosk/env`
do
    export $i
done

# Re-enable screen saver
xset s default

# Re-enable Display Power Management Signaling
xset +dpms

systemctl stop rpi-chromium-kiosk
systemctl disable rpi-chromium-kiosk
systemctl daemon-reload