#!/bin/sh
set -ex

if [ -z "$DISPLAY" ]; then
    DISPLAY=:0.0
fi

if [ -z "$XAUTHORITY" ]; then
    XAUTHORITY=/home/pi/.Xauthority
fi

test -d "/home/pi/.config/lxsession/LXDE-pi/" \
    || mkdir -p "/home/pi/.config/lxsession/LXDE-pi/"

test -f "/home/pi/.config/lxsession/LXDE-pi/autostart" \
    && mv "/home/pi/.config/lxsession/LXDE-pi/autostart" \
        "/home/pi/.config/lxsession/LXDE-pi/autostart.orig"

echo "@xset s off\n@xset -dpms\n@xset s noblank\n@unclutter -idle 0.1" \
    > "/home/pi/.config/lxsession/LXDE-pi/autostart"

while [ -z "$RPI_KIOSK_URL" ]; do
    read -p "Enter Kiosk URL: " RPI_KIOSK_URL
done

echo "DISPLAY      : $DISPLAY"
echo "RPI_KIOSK_URL: $RPI_KIOSK_URL"
echo "XAUTHORITY   : $XAUTHORITY"

test -d /etc/rpi-chromium-kiosk/ || mkdir /etc/rpi-chromium-kiosk/
test -f /etc/rpi-chromium-kiosk/env && rm /etc/rpi-chromium-kiosk/env
echo "DISPLAY=$DISPLAY" >> /etc/rpi-chromium-kiosk/env
echo "XAUTHORITY=$XAUTHORITY" >> /etc/rpi-chromium-kiosk/env
echo "RPI_KIOSK_URL=$RPI_KIOSK_URL" >> /etc/rpi-chromium-kiosk/env

for i in `cat /etc/rpi-chromium-kiosk/env`
do
    export $i
done

systemctl daemon-reload
systemctl enable rpi-chromium-kiosk
systemctl restart lightdm
sleep 5
systemctl start rpi-chromium-kiosk