#!/bin/sh
set -ex 

if [ -f "/home/pi/.config/lxsession/LXDE-pi/autostart.orig" ]; then
    mv "/home/pi/.config/lxsession/LXDE-pi/autostart.orig" \
        "/home/pi/.config/lxsession/LXDE-pi/autostart"
fi

systemctl restart lightdm