#!/bin/sh
set -ex

for i in `cat /etc/rpi-chromium-kiosk/env`
do
    export $i
done

# Re-enable screen saver
xset s default

# Re-enable Display Power Management Signaling
xset +dpms

systemctl stop rpi-chromium-kiosk
systemctl disable rpi-chromium-kiosk
systemctl daemon-reload