#!/bin/sh
set -ex

for i in `cat /etc/rpi-chromium-kiosk/env`
do
    export $i
done

systemctl stop rpi-chromium-kiosk || true
systemctl disable rpi-chromium-kiosk || true
systemctl daemon-reload || true